### ISSUE TITLE
Naming convention for mp11 identifiers

### ISSUE THREAD

**Issue by glenfe** [pdimov/mp11#2]
Suggestion: Instead of both the `mp11` namespace and the `mp_` prefix, is the following naming scheme any better? `mp11::identifier_` 

i.e. Keep the `mp11` namespace, but just use an underscore suffix instead of the current prefix. It still allows you to use keywords (`mp11::if_`) while making the resulting code shorter to read (and type).

(Granted a trailing underscore is not orthodox in most cases, but maybe for a MP library's primitives it may appear sane).

**Comment by odinthenerd** [comment]
Trailing underscore suffix is a somewhat common pattern in TMP in my opinion. Think of int_ bool_ etc. I support the change.

**Comment by pdimov** [comment]
I originally had everything in namespace `boost`, but moved things into `mp11` to allow

```
using namespace boost::mp11;
```

because individual using declarations proved a bit tiresome.

So in the typical case, one sees `mp_unique<mp_transform<...>>`. `mp11::unique_<mp11::transform_<...>>` is not much worse, but it's not better either.

**Comment by glenfe** [comment]
Granted, the using namespace declaration helps. I was thinking that in header-only libraries, where MP11 will no doubt be used most, this may not be desirable to some library developers:

```cpp
namespace library {

using namespace boost::mp11;
// use mp_identifier

} /* library */
```
e.g. They may not want their users to have access to mp11 identifiers within their library namespace. In that case, such hypothetical library developers could do:
* `namespace mp = boost::mp11;` and using `mp::mp_identifier`
* Just using the full`boost::mp11::mp_identifier` everywhere

I guess the former works, and is as tidy as `mp11::identifier_`.
