### ISSUE TITLE
MP11 should be on metabench

### ISSUE THREAD

**Issue by odinthenerd** [pdimov/mp11#3]
I for one would like to see how mp11 stacks up in terms of compile time performance.

**Comment by pdimov** [comment]
Any advice on what I need to do to get mp11 there? Neither Cmake nor Ruby are among my strong suits.

**Comment by odinthenerd** [comment]
I' embarrassingly bad at both too but @brunocodutra was quite helpful to me getting brigand and kvasir on there so now I understand it enough to get myself into trouble. I'll see what I can do.

**Comment by odinthenerd** [comment]
can you list the mp11 equivalent of each of the following algorithms (so I don't get anything wrong):
all
any
at
count_if
erase
filter
find_if
fold_left
fold_right
insert
partition
replace_if
reverse
sort
transform

its ok if you don't have implementations for some we can just leave them out.

**Comment by pdimov** [comment]
```
#include <boost/mp11.hpp>
using namespace boost::mp11
```

and then

```
mp_all_of<L>
mp_any_of<L>
mp_at<L, N> // or mp_at_c<L, N>
mp_count_if<L, P>
template<class L, class N> using erase = mp_append<mp_take<L, N>, mp_drop_c<L, N::value+1>>;
mp_copy_if<L, P>
mp_find_if<L, P>
mp_fold<L, V, F>
mp_reverse_fold<L, V, F>
template<class L, class N, class T> using insert = mp_append<mp_push_back<mp_take<L, N>, T>, mp_drop<L, N>>;
mp_partition<L, P>
mp_replace_if<L, P, W>
mp_reverse<L>
mp_sort<L, P>
mp_transform<F, L>
```

The list type is `mp_list<T...>`.

**Comment by pdimov** [comment]
Incidentally, the benchmarks for `find_if` don't look correct, they look for `n` with the intent to find the last element, but the list contains `n*k+1..n*k+n`, so they don't.

**Comment by brunocodutra** [comment]
Indeed, thanks for pointing that out

**Comment by odinthenerd** [comment]
I think I'm too stupid ;) I just can't seem to get the dependantcy to work. I'll add all the .erb and make a branch where someone else can get it working

**Comment by odinthenerd** [comment]
@pdimov would like to talk a bit about your lib, can you provide an email or follow me on twitter do I can DM you?

**Comment by pdimov** [comment]
Sure, pdimov at pdimov com.

**Comment by brunocodutra** [comment]
@odinthenerd I'll take it from there

**Comment by brunocodutra** [comment]
see ldionne/metabench#174
